### ISSUE TITLE
Color Matrix freezes on iOS

### ISSUE THREAD

**Issue by frankhdz** [openfl/starling#39] opened 2017-01-04 08:51 UTC
When trying to apply a tint filter or any filter for that matter to a sprite the application freezes on iOS.

**Comment by mayakwd** [comment] 2017-01-18 10:19
Same, debug log shows nothing

**Comment by mayakwd** [comment] 2017-01-19 05:43
@jgranick, @vroad any suggestions?

**Comment by jgranick** [comment] 2017-01-19 16:01
Perhaps this is related to framebuffer performance?

**Comment by mayakwd** [comment] 2017-01-22 11:01
Unfortunately, it gives me nothing, can you, please, more specific? What should I try to do to fix it?

**Comment by alanlanglois** [comment] 2017-10-26 09:57
I'm using the blurFilter this way: 
displayObject.filter = BlurFilter.createDropShadow(0, 1, 0x0, 0.6, 1.5 );

But it freezes this ios app instatanetly.

It's working fine on Android & HTML5.

Also I got this log in Xcode after a while: 
`Warning: frames inside the texture's region are unsupported.
`
But I'm not sure it's related, because it's a warning it shouldn't freeze the app. 
I don't have this warning when targeting HTML5 though. 

The app stays freezed and the only way to unfreeze it is to restart the app (the starling stats doesn't change and buttons are unclickable).

**Comment by jgranick** [comment] 2018-05-11 00:57
Has anyone tried this more recently? I believe this was caused by a more serious issue in iOS framebuffer support, that was resolved in our use of SDL in Lime. I'm going to close because I believe that was the cause, but please let me know if this does occur with more recent versions

**Closed by jgranick** 2018-05-11 00:57 UTC
